// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExcelDnaDoc")]
[assembly: AssemblyProductAttribute("ExcelDnaDoc")]
[assembly: AssemblyDescriptionAttribute("command-line utility to create a compiled HTML Help Workshop file (.chm) for ExcelDna")]
[assembly: AssemblyVersionAttribute("0.2.3")]
[assembly: AssemblyFileVersionAttribute("0.2.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.3";
        internal const string InformationalVersion = "0.2.3";
    }
}
