// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExcelDna.Documentation")]
[assembly: AssemblyProductAttribute("ExcelDnaDoc")]
[assembly: AssemblyDescriptionAttribute("command-line utility to create a compiled HTML Help Workshop file (.chm) for ExcelDna")]
[assembly: AssemblyVersionAttribute("0.1.10")]
[assembly: AssemblyFileVersionAttribute("0.1.10")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.10";
    }
}
