// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("ExcelDna.Documentation")]
[assembly: AssemblyProductAttribute("ExcelDnaDoc")]
[assembly: AssemblyDescriptionAttribute("command-line utility to create a compiled HTML Help Workshop file (.chm) for ExcelDna")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "ExcelDna.Documentation";
        internal const System.String AssemblyProduct = "ExcelDnaDoc";
        internal const System.String AssemblyDescription = "command-line utility to create a compiled HTML Help Workshop file (.chm) for ExcelDna";
        internal const System.String AssemblyVersion = "1.1.0";
        internal const System.String AssemblyFileVersion = "1.1.0";
    }
}
