//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDnaDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelDnaDoc.Html.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CategoryTemplate {
            get {
                object obj = ResourceManager.GetObject("CategoryTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CommandListTemplate {
            get {
                object obj = ResourceManager.GetObject("CommandListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CommandTemplate {
            get {
                object obj = ResourceManager.GetObject("CommandTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FunctionTemplate {
            get {
                object obj = ResourceManager.GetObject("FunctionTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	width: 100%;
        ///	margin: 0px 0px 0px 0px;
        ///	font-family: Verdana, Arial, Helvetica, sans-serif;
        ///	font-size: 70%;
        ///}
        ///
        ///h1, h3, h4
        ///{
        ///	margin-bottom: .4em;
        ///	margin-top: 1em;
        ///}
        ///
        ///h1
        ///{
        ///	font-size: 120%;
        ///	margin-top: 0em;
        ///}
        ///
        ///h3
        ///{
        ///	color: darkblue;
        ///	font-size: 115%;
        ///}
        ///
        ///h4
        ///{
        ///	color: darkblue;
        ///	font-size: 100%;
        ///}
        ///
        ///div.table
        ///{
        ///	text-align: center;
        ///}
        ///
        ///table
        ///{
        ///	font-size: 100%;
        ///	border-collapse: collapse;
        ///	width: 93%;
        ///}
        ///
        ///th
        ///{
        ///	background-color: #cccccc;
        ///	color: #000000;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string helpstyle {
            get {
                return ResourceManager.GetString("helpstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MethodListTemplate {
            get {
                object obj = ResourceManager.GetObject("MethodListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProjectFileTemplate {
            get {
                object obj = ResourceManager.GetObject("ProjectFileTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TableOfContentsTemplate {
            get {
                object obj = ResourceManager.GetObject("TableOfContentsTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
